### ISSUE TITLE
WARNING: could not import DiffEqSensitivity.SensitivityADPassThrough into Main

### ISSUE THREAD

**Issue by samuela** [SciML/DiffEqSensitivity.jl#306]
The latest docs [here](https://docs.sciml.ai/stable/analysis/sensitivity/#Sensitivity-Algorithms-1) suggest that it should be possible to use `SensitivityADPassThrough` for "backprop through the solver", but I'm not able to import it:
```julia
julia> import DiffEqSensitivity: SensitivityADPassThrough
WARNING: could not import DiffEqSensitivity.SensitivityADPassThrough into Main

julia> import DifferentialEquations: SensitivityADPassThrough
WARNING: could not import DifferentialEquations.SensitivityADPassThrough into Main
```

Also OOC what's the distinction between ReverseDiffAdjoint, TrackerAdjoint, ZygoteAdjoint, and SensitivityADPassThrough? It seems as though they all do the same thing, just with different AD frameworks. Wouldn't SensitivityADPassThrough subsume all of these use cases?

**Comment by ChrisRackauckas** [comment]
>Also OOC what's the distinction between ReverseDiffAdjoint, TrackerAdjoint, ZygoteAdjoint, and SensitivityADPassThrough? It seems as though they all do the same thing, just with different AD frameworks. Wouldn't SensitivityADPassThrough subsume all of these use cases?

`ReverseDiffAdjoint` calls `ReverseDiff` on `solve` with `SensitivityADPassThrough`. If `SensitivityADPassThrough` didn't exist, then the adjoint system would recursively detect it's in an adjoint, start the adjoint process, setup ReverseDiff, call solve, detect it's in an adjoint, ... . So `SensitivityADPassThrough` is somewhat of an internal detail that what it really means is, ignore all of our adjoint overloads and work like it doesn't exist. We expose it to the user in case they want to just use/test the AD system bypassing any adjoint overload behavior.

**Comment by samuela** [comment]
I see. What is the recommended approach to doing reverse-mode "backprop through the sovler" with DifferentialEquations? It sounds like ZygoteAdjoint doesn't work atm, and Tracker.jl seems to be obsolete. 

Also if I were to desire to use `SensitivityADPassThrough` how would I go about importing it?

**Comment by ChrisRackauckas** [comment]
>Also if I were to desire to use SensitivityADPassThrough how would I go about importing it?

I think it's in DiffEqBase. I agree this is a bit odd (since it's a part of the dispatching system of `solve` itself), so we might want to add it to the namespace just like the other sensitivity algorithm choices to make it easier.

>I see. What is the recommended approach to doing reverse-mode "backprop through the sovler" with DifferentialEquations? It sounds like ZygoteAdjoint doesn't work atm, and Tracker.jl seems to be obsolete.

Tracker.jl is fine (and a few new people are maintaining it, so it's not dead), but really slow. But ReverseDiff tends to just be better. What I recommend is... I was waiting to merge https://github.com/SciML/DiffEqSensitivity.jl/pull/267 until https://github.com/JuliaDiff/ReverseDiff.jl/pull/134, but this is useful enough that I am done waiting, so I just tagged a new version of ReverseDiff with my fixes in there, and then will merge that PR with a new `using DistributionsAD` to make it pass, and tag a new version here so that `ReverseDiffAdjoint` works by default. Then I'm going to open an issue saying that when https://github.com/JuliaDiff/ReverseDiff.jl/pull/134 merges we should remove DistributionsAD to reduce `using` times, but with that, I will recommend ReverseDiffAdjoint in about 2 hours.

**Comment by samuela** [comment]
> Tracker.jl is fine (and a few new people are maintaining it, so it's not dead), but really slow. But ReverseDiff tends to just be better. What I recommend is... I was waiting to merge #267 until JuliaDiff/ReverseDiff.jl#134, but this is useful enough that I am done waiting, so I just tagged a new version of ReverseDiff with my fixes in there, and then will merge that PR with a new using DistributionsAD to make it pass, and tag a new version here so that ReverseDiffAdjoint works by default. Then I'm going to open an issue saying that when JuliaDiff/ReverseDiff.jl#134 merges we should remove DistributionsAD to reduce using times, but with that, I will recommend ReverseDiffAdjoint in about 2 hours.

I'm simultaneously confused and excited!

**Comment by ChrisRackauckas** [comment]
This is getting fixed by https://github.com/SciML/DiffEqBase.jl/pull/556
