### ISSUE TITLE
Integration with callbacks?

### ISSUE THREAD

**Issue by ikirill** [SciML/DiffEqSensitivity.jl#4]
In Sundials.jl there's a way to get parameter sensitivities for ODEs with discontinuities, but when I tried the same approach with ODELocalSensitivityProblem, there either doesn't seem to be a way to do it, or it's undocumented and I didn't find it. The obvious thing didn't work:

```
using DifferentialEquations

f = @ode_def FFF begin
    dx = -a
    dy = b
end a=>2.0 b=>1.0

cb = ContinuousCallback((t,u,i) -> u[1], (args...)->(println("Stopped.");f.b=0.0))
prob = ODELocalSensitivityProblem(f, [1.0, 0.0], (0.0, 1.0), callback=cb)
sol = solve(prob, DP8())
display(sol)
```

The solution is
```
 [-1.0, 0.5, -1.0, 0.0, 0.0, 1.0]                            
```
and the derivative `dy/da` is reported as zero, but should be -0.25. This is an issue whenever the callback changes some state (here b) and the trigger function depends on the state.

**Comment by ChrisRackauckas** [comment]
Hmm, I didn't think about this. How exactly is the discontinuity supposed to be handled? It should apply the change to the derivatives, but how exactly?

**Comment by felixlen** [comment]
Sensitivities have to be updated at every discontinuity, see for example equations 4.48a and 4.48b in [this thesis](https://mathopt.de/PUBLICATIONS/Kirches2006.pdf).

**Comment by ChrisRackauckas** [comment]
Updated version:

```julia
using DiffEqSensitivity, ParameterizedFunctions
using OrdinaryDiffEq, Calculus

f = @ode_def AAA begin
    dx = -a
    dy = b
end a b

cb = ContinuousCallback((u,t,i) -> u[1], (integrator)->(println("Stopped.");integrator.p[2]=0.0))
p = [2.0, 1.0]
prob = ODELocalSensitivityProblem(f, [1.0, 0.0], (0.0, 1.0), p)
sol = solve(prob, Tsit5(), callback=cb)

DiffEqBase.has_syms(::DiffEqSensitivity.ODELocalSensitvityFunction) = false
using Plots; gr(); plot(sol,vars=[1,2])

ls = extract_local_sensitivities(sol, length(sol))[2]
ls

#> ls
# 2-element Array{Array{Float64,1},1}:
# [-1.0, 0.0]
# [0.0, 1.0]

function test_f(p)
  prob = ODEProblem(f,eltype(p).([1.0,0.0]),eltype(p).((0.0,1.0)),copy(p))
  solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14,callback=cb,save_everystep=false)[end]
end
p = [2.0, 1.0]
findiff = Calculus.finite_difference_jacobian(test_f,p)
findiff
#> findiff
#2×2 Array{Float64,2}:
# -1.0   5.50028e-11
# -0.25  0.5
```

**Comment by ChrisRackauckas** [comment]
>In Sundials.jl there's a way to get parameter sensitivities for ODEs with discontinuities

Where is this documented?

**Comment by ChrisRackauckas** [comment]
https://arxiv.org/pdf/1905.10403.pdf is the most clear definition of this result. I see two ways to handle this. The first, which I'm less bullish on, is to try to have a place in the DiffEqBase callback mechanism to inject modifiers so that if we're in adjoint mode we can check for `u_modified!` and then change the adjoint state ourselves. This has many issues though, one being the ease of composability and the maintenance of something so deep and so specific, but the other is that the `condition` isn't guaranteed to be correct if the first set of states does not match the original differential equation. In fact, if someone did `condition(u,t,integrator) = sum(u)`, the backwards condition would then have all kinds of adjoint stuff in it and be incorrect. That's not good!

So the second way I have in mind is somewhat tricky but would do the job quite nicely. Notice that in algorithm A.3 of https://arxiv.org/pdf/1905.10403.pdf it's defined to do a condition whenever there was a forward event. So we need some way to track a callback going forward. I propose simply wrapping the callbacks in something that keeps their condition going forward, but then tracks their times in the `affect!` function. This can be done by making a `TrackingCallback` that simply repeats the `condition` function and then wraps the `affect!` function to push to some arrays that capture the state.

Then the reverse needs to happen. For this, each TrackingCallback in the AdjointProblem should make a `AdjointCallback`. All of these would be `DiscreteCallback`s, since the event times are known (since they are simply at the tracked times of the even going forward). The `affect!` is a vector-Jacobian callback of the `affect!` function of the original callback going forwards (see (13) in https://arxiv.org/pdf/1905.10403.pdf for the equation), wrapped with a `FakeIntegrator`:

https://github.com/SciML/DiffEqGPU.jl/blob/master/src/DiffEqGPU.jl#L86-L90

What I mean is the following. The `w` from the paper is a function that is:

```julia
function w(u,p,t)
  integrator = FakeIntegrator(u,p,t)
  affect!(integrator)
  u - integrator.u
end
```

(since it's the change in the state). So then the affect of the `AdjointCallback` would be to calculate the vjps of this function and then update the state of the real integrator.
