### ISSUE TITLE
diffeq_adjoint won't train for dynamical ODE

### ISSUE THREAD

**Issue by jgreener64** [SciML/DiffEqSensitivity.jl#64]
Posting here after asking on Gitter.

I was trying to make a `SecondOrderODEProblem` work in a neural ODE layer. This is what I have so far:

```julia
using DifferentialEquations
using Flux
using DiffEqFlux

model = Chain(Dense(2, 50, tanh), Dense(50, 2))

u0 = Float32[0.; 2.]
du0 = Float32[0.; 0.]
tspan = (0.0f0, 1.0f0)
t = range(tspan[1], tspan[2], length=20)

p1 = param(Flux.data(DiffEqFlux.destructure(model)))
ps = Flux.params(p1)

function f(du, u, p, t)
    println("u is ", u, " du is ", du)
    return DiffEqFlux.restructure(model, p)(u)
end

prob = SecondOrderODEProblem{false}(f, du0, u0, tspan, p1)

function predict_adjoint()
    diffeq_adjoint(p1, prob, Tsit5(), u0=(du0, u0), saveat=t, abstol=1e-8, reltol=1e-6)
end

correct_pos = Float32.(transpose(hcat(collect(0:0.05:1)[2:end], collect(2:-0.05:1)[2:end])))

loss_n_ode() = sum(abs2, correct_pos .- predict_adjoint()[1:2, :])

data = Iterators.repeated((), 1000)
opt = ADAM(0.1)

cb = function ()
    println(loss_n_ode())
    loss_n_ode() < 0.01 && Flux.stop()
end

Flux.train!(loss_n_ode, ps, data, opt, cb=cb)
```

The ODE seems to run okay, as in running `diffeq_adjoint` works. But then when I try to run the `Flux.train!` line I get errors about `zero` and `similar` not being defined for the relevant argument types, and if I try to fix these I get `ERROR: type DynamicalODEFunction has no field jac`.

It seems that the neural ODE layer is not implemented for this ODE type. It has been pointed out that `diffeq_rd` should work in this case, so I'll give it a go.

**Comment by SteffenPL** [comment]
I have the same problem.

In the code, the function `sol.prob.f` is considered to be an right hand side,
however, for **DynamicalODEProblem**s that function is of type
DynamicalODEFunction and it would be required to use `sol.prob.f.f1`  and `sol.prob.f.f2` 
in the construction of the ODEProblem.



Here is a minimal example

`using DifferentialEquations

using Plots

f1(x,v,p,t) = v[:] 
f2(x,v,p,t) = -p * x[1]

x0 = [1.]
v0 = [-1.]
p = 2

prob = DynamicalODEProblem(f1!,f2!,x0,v0,(0.0, 2.0),p)
sol = solve(prob,Euler(),dt=0.1)

using DiffEqSensitivity

g(u,p,t) = sum(abs.(u[1,:] .- 1)) + abs(p)

sense = adjoint_sensitivities(sol,Euler(),g,nothing;sensealg=SensitivityAlg(backsolve=true))
`

It yields the error message:
**type DynamicalODEFunction has no field colorvec**

it is caused by line 208 in _DiffEqSensitivity\xlGSs\src\adjoint_sensitivity.jl_

`sense = ODEAdjointSensitivityFunction(g,u0,
                                        p,alg,discrete,
                                        sol,dg,checkpoints,tspan,f.colorvec)`

where `f` is defined as `f = sol.prob.f`.

I can post the full error log, but in this case it is quite clear where the error comes from.

**Comment by ChrisRackauckas** [comment]
It's because the adjoint pulls a lot of these pieces from the ODEFunction to support fast sparse stiff etc., but those don't exist in the DynamicalODEFunction. We can workaround that though.

**Comment by ChrisRackauckas** [comment]
Fixed.
